name: 'Install Rust toolchain'
description: 'Install both `rustup` and a Rust toolchain'

inputs:
  toolchain:
    description: 'Default toolchan to install'
    required: false
    default: 'stable'

runs:
  using: "composite"
  steps:
    - name: Update Rustup
      # Needed for now to get 1.24.2 which fixes a bug in 1.24.1 that causes issues on Windows.
      if: runner.os == 'Windows'
      run: rustup self update
    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup update ${{ inputs.toolchain }} --no-self-update
        rustup default ${{ inputs.toolchain }}
    - name: Set Env
      run: |
        # Save disk space by avoiding incremental compilation,
        # and also we don't use any caching so incremental wouldn't help anyway.
        echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV
        # Turn down debuginfo from 2 to 1 to help save disk space
        echo "CARGO_PROFILE_DEV_DEBUG=1" >> $GITHUB_ENV
        echo "CARGO_PROFILE_TEST_DEBUG=1" >> $GITHUB_ENV
    - name: MacOS Env
      if: runner.os == 'macOS'
      run: |
        echo "CARGO_PROFILE_DEV_SPLIT_DEBUGINFO=unpacked" >> $GITHUB_ENV
        echo "CARGO_PROFILE_TEST_SPLIT_DEBUGINFO=unpacked" >> $GITHUB_ENV
